services:
  php81-fpm:
    container_name: laradock-lite-php81-fpm
    build:
      context: ./php-fpm
      args:
        - PHP_VERSION=8.1
        - PUID=${PHP_FPM_PUID}
        - PGID=${PHP_FPM_PGID}
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
      - ./php-fpm/laravel.ini:/usr/local/etc/php/conf.d/laravel.ini
      - ./php-fpm/opcache.ini:/usr/local/etc/php/conf.d/opcache.ini
      - ./php-fpm/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ./php-fpm/xlaravel.pool.conf:/usr/local/etc/php-fpm.d/xlaravel.pool.conf
    expose:
      - "9000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - "nginx"

  php82-fpm:
    container_name: laradock-lite-php82-fpm
    build:
      context: ./php-fpm
      args:
        - PHP_VERSION=8.2
        - PUID=${PHP_FPM_PUID}
        - PGID=${PHP_FPM_PGID}
        - ADDITIONAL_PHP_EXTENSIONS=ftp
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
      - ./php-fpm/laravel.ini:/usr/local/etc/php/conf.d/laravel.ini
      - ./php-fpm/opcache.ini:/usr/local/etc/php/conf.d/opcache.ini
      - ./php-fpm/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ./php-fpm/xlaravel.pool.conf:/usr/local/etc/php-fpm.d/xlaravel.pool.conf
    expose:
      - "9000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - "nginx"

  php83-fpm:
    container_name: laradock-lite-php83-fpm
    build:
      context: ./php-fpm
      args:
        - PHP_VERSION=8.3
        - PUID=${PHP_FPM_PUID}
        - PGID=${PHP_FPM_PGID}
        - ADDITIONAL_PHP_EXTENSIONS=ftp
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
      - ./php-fpm/laravel.ini:/usr/local/etc/php/conf.d/laravel.ini
      - ./php-fpm/opcache.ini:/usr/local/etc/php/conf.d/opcache.ini
      - ./php-fpm/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ./php-fpm/xlaravel.pool.conf:/usr/local/etc/php-fpm.d/xlaravel.pool.conf
    expose:
      - "9000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - "nginx"

  nginx:
    container_name: laradock-lite-nginx
    build:
      context: ./nginx
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
      - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
      - ${NGINX_HOST_SITES_PATH}:/etc/nginx/sites-available
    ports:
      - "${NGINX_HOST_HTTP_PORT}:80"

  mariadb:
    container_name: laradock-lite-mariadb
    build:
      context: ./mariadb
      args:
        - TZ=${MARIADB_TIME_ZONE}
        - VERSION=${MARIADB_VERSION}
    volumes:
      - ${DATA_PATH_HOST}/mariadb:/var/lib/mysql
      - ${MARIADB_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d
    ports:
      - "${MARIADB_PORT}:3306"
    environment:
      - MYSQL_DATABASE=${MARIADB_DATABASE}
      - MYSQL_USER=${MARIADB_USER}
      - MYSQL_PASSWORD=${MARIADB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}

  postgres:
    container_name: laradock-lite-postgres
    build:
      context: ./postgres
      args:
        - POSTGRES_VERSION=${POSTGRES_VERSION}
    volumes:
      - ${DATA_PATH_HOST}/postgres:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - TZ=${POSTGRES_TIME_ZONE}

  adminer:
    container_name: laradock-lite-adminer
    build:
      context: ./adminer
    ports:
      - "${ADMINER_HOST_HTTP_PORT}:8080"

  redis:
    container_name: laradock-lite-redis
    build:
      context: ./redis
    volumes:
      - ${DATA_PATH_HOST}/redis:/data
    ports:
      - "${REDIS_PORT}:6379"

  redis-webui:
    container_name: laradock-lite-redis-webui
    build:
      context: ./redis-webui
    environment:
      - ADMIN_USER=${REDIS_WEBUI_USERNAME}
      - ADMIN_PASS=${REDIS_WEBUI_PASSWORD}
      - REDIS_1_HOST=${REDIS_WEBUI_CONNECT_HOST}
      - REDIS_1_PORT=${REDIS_WEBUI_CONNECT_PORT}
    ports:
      - "${REDIS_WEBUI_PORT}:80"
    depends_on:
      - redis

  mailhog:
    container_name: laradock-lite-mailhog
    build:
      context: ./mailhog
    logging:
      driver: 'none'
    ports:
      - "1025:1025"
      - "8025:8025"

  sftp:
    container_name: laradock-lite-sftp
    build:
      context: ./sftp
    volumes:
      - ./sftp/sftp_key.pub:/home/foo/.ssh/keys/sftp_key.pub
    ports:
      - "2222:22"
    command: foo::::upload
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
